### ISSUE TITLE
Oil deposits don't work

### ISSUE THREAD

**Issue by 4EEZE** [DrMango14/Create-The_Factory_Must_Grow#51]
In the last changelog update for 1.19.2 (0.8.0b) it said they were fixed, but I still can't do anything with them.
And also the fluids from this mod can't interact with the creative fluid tank.
But the mod itself is great.
![изображение](https://github.com/DrMango14/Create-The_Factory_Must_Grow/assets/76529316/dd3c5ffd-dfd6-4e34-977f-32f95e3b7c49)

**Comment by Jiexgx** [comment]
Where is your pump jack?

**Comment by 4EEZE** [comment]
I've built it several times in different ways, including how it's done in the guide, but it doesn't change anything

**Comment by michalcz17** [comment]
I have the same problem too, in survival and even in creative, version 1.19.2 (both 0.8.0 and 0.8.0b). Is there any update of this issue?

**Comment by millennIumAMbiguity** [comment]
You need a pump jack. Don't forget to glue it.
https://youtu.be/PG8rxNBJKXM?si=RqwMfU4bnRkpEZIh

**Comment by 4EEZE** [comment]
Yes, it worked with the glue, thanks
